name: Schema deploy gh-pages

on:
  push:
    branches:
      - main  # Only run this workflow on pushes to the main branch

jobs:
  build:
    # Run the job only on `push` events to `main` branch
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: NPM Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
            ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install
      - name: Configure Git User
        run: |
          git config  user.name "GitHub Actions"
          git config  user.email "actions@github.com"
      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

      - name: Deploy to GitHub Pages
        run: npm run deploy
